FILENAME: 1182_5.py, LINE: 6 (Too general exception)
FILENAME: 2334_6.py, LINE: 18 (Too general exception)
FILENAME: 401_0.py, LINE: 5 (Too general exception)
