FILENAME: 105421_15.py, LINE: 10 (Too general exception)
FILENAME: 121122_6.py, LINE: 27 (Too general exception)
FILENAME: 121822_66.py, LINE: 5 (Too general exception)
FILENAME: 135823_79.py, LINE: 14 (Empty exception detected)
FILENAME: 148625_50.py, LINE: 17 (Too general exception)
FILENAME: 17322_5.py, LINE: 5 (Too general exception)
FILENAME: 19014_5.py, LINE: 6 (Too general exception)
FILENAME: 19044_53.py, LINE: 27 (Too general exception)
FILENAME: 19064_55.py, LINE: 5 (Empty exception detected)
FILENAME: 19104_59.py, LINE: 17 (Too general exception)
FILENAME: 21958_107.py, LINE: 19 (Empty exception detected)
FILENAME: 61415_6.py, LINE: 18 (Too general exception)
FILENAME: 64616_0.py, LINE: 7 (Empty exception detected)
FILENAME: 74118_2.py, LINE: 10 (Too general exception)
FILENAME: 75818_35.py, LINE: 9 (Too general exception)
FILENAME: 77218_5.py, LINE: 28 (Too general exception)
FILENAME: 8741_0.py, LINE: 5 (Too general exception)
FILENAME: 98320_40.py, LINE: 8 (Too general exception)
FILENAME: 98320_40.py, LINE: 15 (Too general exception)
